openapi: 3.0.3
info:
  title: Emergency notification system
  description: |-
    This is a REST API for emergency notification system project. 
    You can find out more about it at [github](https://github.com/Lookingforcommit/emergency_notification_system).
    All the endpoints (except for authorization and authentication) require user JWT token to be provided. JWT token 
    should be provided in http headers in format: "Authorization: YOUR_JWT_TOKEN"
  contact:
    email: artyomsh628691@gmail.com
  version: 1.0.0
tags:
  - name: user
    description: User authorization and authentication
  - name: recipients
    description: Manage your recipients
  - name: groups
    description: Manage your recipient groups
  - name: templates
    description: Manage your notification templates
  - name: notifications
    description: Notifications endpoints
paths:
  /user/create:
    $ref: "paths/user/user-create.yaml"
  /user/login:
    $ref: "paths/user/user-login.yaml"
  /user/modifyUser:
    $ref: "paths/user/user-modifyUser.yaml"
  /user/refreshToken:
    $ref: "paths/user/user-refreshToken.yaml"
  /user:
    $ref: "paths/user/user.yaml"

  /recipients/create:
    $ref: "/paths/recipients/recipients-create.yaml"
  /recipients/all:
    $ref: "/paths/recipients/recipients-all.yaml"
  /recipients:
    $ref: "/paths/recipients/recipients.yaml"
  /recipients/confirmCreation:
    $ref: "/paths/recipients/recipients-confirmCreation.yaml"
  /recipients/modifyRecipient:
    $ref: "/paths/recipients/recipients-modifyRecipient.yaml"
  /recipients/deleteRecipient:
    $ref: "/paths/recipients/recipients-deleteRecipient.yaml"

  /groups/create:
    $ref: "/paths/groups/groups-create.yaml"
  /groups/all:
    $ref: "/paths/groups/groups-all.yaml"
  /groups/active:
    $ref: "/paths/groups/groups-active.yaml"
  /groups:
    $ref: "/paths/groups/groups.yaml"
  /groups/recipients:
    $ref: "/paths/groups/groups-recipients.yaml"
  /groups/confirmCreation:
    $ref: "/paths/groups/groups-confirmCreation.yaml"
  /groups/modifyGroup:
    $ref: "/paths/groups/groups-modifyGroup.yaml"
  /groups/addRecipient:
    $ref: "/paths/groups/groups-addRecipient.yaml"
  /groups/deleteRecipient:
    $ref: "/paths/groups/groups-deleteRecipient.yaml"
  /groups/deleteGroup:
    $ref: "/paths/groups/groups-deleteGroup.yaml"

  /templates/create:
    $ref: "/paths/templates/templates-create.yaml"
  /templates:
    $ref: "/paths/templates/templates.yaml"
  /templates/all:
    $ref: "/paths/templates/templates-all.yaml"
  /templates/confirmCreation:
    $ref: "/paths/templates/templates-confirmCreation.yaml"
  /templates/modifyTemplate:
    $ref: "/paths/templates/templates-modifyTemplate.yaml"
  /templates/deleteTemplate:
    $ref: "/paths/templates/templates-deleteTemplate.yaml"

  /notifications/all:
    $ref: "paths/notifications/notifications-all.yaml"
  /notifications/pending:
    $ref: "paths/notifications/notifications-pending.yaml"
  /notifications/completed:
    $ref: "paths/notifications/notifications-completed.yaml"
  /notifications/send:
    $ref: "paths/notifications/notifications-send.yaml"
  /notifications/cancelNotification:
    $ref: "paths/notifications/notifications-cancelNotification.yaml"
security:
  - bearerAuth: []
