openapi: 3.0.3
info:
  title: Emergency notification system
  description: |-
    This is a REST API for emergency notification system project. 
    You can find out more about it at [github](https://github.com/Lookingforcommit/emergency_notification_system).
    All the endpoints (except for authorization and authentication) require user JWT token to be provided. JWT token 
    should be provided in http headers in format: "Authorization: YOUR_JWT_TOKEN"
  contact:
    email: artyomsh628691@gmail.com
  version: 1.0.0
tags:
  - name: user
    description: User authorization and authentication
  - name: recipients
    description: Manage your recipients
  - name: groups
    description: Manage your recipient groups
  - name: templates
    description: Manage your notification templates
  - name: notifications
    description: Notifications endpoints
paths:
  /user/create:
    $ref: "paths/user/user-create.yaml"
  /user/login:
    $ref: "paths/user/user-login.yaml"
  /user/modifyUser:
    $ref: "paths/user/user-modifyUser.yaml"
  /user/refreshToken:
    $ref: "paths/user/user-refreshToken.yaml"
  /user:
    $ref: "paths/user/user.yaml"

  /recipients/create:
    $ref: "/paths/recipients/recipients-create.yaml"
  /recipients/{recipient_id}:
    $ref: "/paths/recipients/recipients-{recipient_id}.yaml"
  /recipients:
    $ref: "/paths/recipients/recipients.yaml"
  /recipients/confirmCreation/{draft_id}:
    $ref: "/paths/recipients/recipients-confirmCreation-{draft_id}.yaml"
  /recipients/modifyRecipient/{recipient_id}:
    $ref: "/paths/recipients/recipients-modifyRecipient-{recipient_id}.yaml"
  /recipients/deleteRecipient/{recipient_id}:
    $ref: "/paths/recipients/recipients-deleteRecipient-{recipient_id}.yaml"

  /groups/create:
    $ref: "/paths/groups/groups-create.yaml"
  /groups:
    $ref: "/paths/groups/groups.yaml"
  /groups/active:
    $ref: "/paths/groups/groups-active.yaml"
  /groups/{group_id}:
    $ref: "/paths/groups/groups-{group_id}.yaml"
  /groups/recipients/{group_id}:
    $ref: "/paths/groups/groups-recipients-{group_id}.yaml"
  /groups/confirmCreation/{draft_id}:
    $ref: "/paths/groups/groups-confirmCreation-{draft_id}.yaml"
  /groups/modifyGroup/{group_id}:
    $ref: "/paths/groups/groups-modifyGroup-{group_id}.yaml"
  /groups/{group_id}/recipients/{recipient_id}:
    $ref: "/paths/groups/groups-{group_id}-recipients-{recipient_id}.yaml"
  /groups/deleteGroup/{group_id}:
    $ref: "/paths/groups/groups-deleteGroup-{group_id}.yaml"

  /templates/create:
    $ref: "/paths/templates/templates-create.yaml"
  /templates/{template_id}:
    $ref: "/paths/templates/templates-{template_id}.yaml"
  /templates:
    $ref: "/paths/templates/template.yaml"
  /templates/confirmCreation/{draft_id}:
    $ref: "/paths/templates/templates-confirmCreation-{draft_id}.yaml"
  /templates/modifyTemplate/{template_id}:
    $ref: "/paths/templates/templates-modifyTemplate-{template_id}.yaml"
  /templates/deleteTemplate/{template_id}:
    $ref: "/paths/templates/templates-deleteTemplate-{template_id}.yaml"

  /notifications:
    $ref: "paths/notifications/notifications.yaml"
  /notifications/pending:
    $ref: "paths/notifications/notifications-pending.yaml"
  /notifications/completed:
    $ref: "paths/notifications/notifications-completed.yaml"
  /notifications/send:
    $ref: "paths/notifications/notifications-send.yaml"
  /notifications/{notification_id}:
    $ref: "paths/notifications/notifications-{notification_id}.yaml"
security:
  - bearerAuth: []
