openapi: 3.0.3
info:
  title: Project schemas
  version: 1.0.0
paths:
  {}
components:
  schemas:
    User:
      description: User login schema
      type: object
      properties:
        name:
          type: string
        password:
          type: string
      required:
        - name
        - password
      additionalProperties: false

    JWTString:
      description: |
        JWT Schema used for user authorization and authentication <br>
        JWT is built in the following format: <br>
        f"base64urlEncoding(header) + '.' + base64urlEncoding(payload) + '.' + base64urlEncoding(signature)" <br>
        header is an object containing -> {"alg": {CHOSEN_ALG}, "typ": "JWT"} <br>
        payload is an object containing the data of jwt <br>
        signature is an encoded with a PRIVATE_KEY object by our CHOSEN_ALG from the following format: <br>
        CHOSEN_ALG(PRIVATE_KEY, base64urlEncoding(header) + '.' + base64urlEncoding(payload))
      type: string
      example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

    BaseRecipient:
      description: Base schema for all Recipient schemas
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        email:
          type: string
        phone_number:
          type: string
          description: "Recipient phone number in international format"
          example: "+12345"
        telegram_id:
          type: integer
          description: "User id of the recipient account. You can view it if you turn on the
                        advanced_settings/experimental/show_peer_ids option"
          example: "1251054162"
      required:
        - name

    ReturnedRecipient:
      allOf:
        - $ref: "#/components/schemas/BaseRecipient"
        - description: Base schema for all Recipient schemas returned by the server
          type: object
          additionalProperties: true
          properties:
            master_id:
              type: string
          required:
            - master_id

    RecipientWithoutId:
      allOf:
        - $ref: "#/components/schemas/BaseRecipient"
        - description: Recipient object without recipient_id. Used to represent user json payloads
          type: object
          additionalProperties: true

    RecipientDraft:
      allOf:
        - $ref: "#/components/schemas/ReturnedRecipient"
        - description: Recipient draft object. Used to represent a Recipient object pending for creation
          type: object
          additionalProperties: true
          properties:
            draft_id:
              type:
                string
          required:
            - draft_id

    RecipientWithId:
      allOf:
        - $ref: "#/components/schemas/ReturnedRecipient"
        - description: Recipient object with recipient_id. Used to represent server-generated objects
          type: object
          additionalProperties: true
          properties:
            recipient_id:
              type:
                string
          required:
            - recipient_id

    RecipientWithIdList:
      type: array
      items:
        $ref: "#/components/schemas/RecipientWithId"

    BaseRecipientGroup:
      description: Base schema for all RecipientGroup schemas
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        notification_template_id:
          type: string
        active:
          type: boolean
      required:
        - name
        - active

    ReturnedRecipientGroup:
      allOf:
        - $ref: "#/components/schemas/BaseRecipientGroup"
        - description: Base schema for all RecipientGroup schemas returned by the server
          type: object
          additionalProperties: true
          properties:
            master_id:
              type: string
          required:
            - master_id

    RecipientGroupWithoutId:
      allOf:
        - $ref: "#/components/schemas/BaseRecipientGroup"
        - description: RecipientGroup object without recipientGroupId. Used to represent user json payloads
          type: object
          additionalProperties: true

    RecipientGroupDraft:
      allOf:
        - $ref: "#/components/schemas/ReturnedRecipientGroup"
        - description: Recipient draft object. Used to represent a RecipientGroup object pending for creation
          type: object
          additionalProperties: true
          properties:
            draft_id:
              type:
                string
          required:
            - draft_id

    RecipientGroupWithId:
      allOf:
        - $ref: "#/components/schemas/ReturnedRecipientGroup"
        - description: RecipientGroup object with recipientGroupId. Used to represent server-generated objects
          type: object
          additionalProperties: true
          properties:
            recipient_group_id:
              type:
                string
          required:
            - recipient_group_id

    RecipientGroupWithIdList:
      type: array
      items:
        $ref: "#/components/schemas/RecipientGroupWithId"

    BaseNotificationTemplate:
      description: Base schema for all NotificationTemplate schemas
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        message_text:
          type: string
      required:
        - name

    ReturnedNotificationTemplate:
      allOf:
        - $ref: "#/components/schemas/BaseNotificationTemplate"
        - description: Base schema for all NotificationTemplate schemas returned by the server
          type: object
          additionalProperties: true
          properties:
            master_id:
              type: string
          required:
            - master_id

    NotificationTemplateWithoutId:
      allOf:
        - $ref: "#/components/schemas/BaseNotificationTemplate"
        - description: NotificationTemplate object without notificationTemplateId. Used to represent user json payloads
          type: object
          additionalProperties: true

    NotificationTemplateDraft:
      allOf:
        - $ref: "#/components/schemas/ReturnedNotificationTemplate"
        - description: NotificationTemplate draft object. Used to represent a NotificationTemplate object pending
                       for creation
          type: object
          additionalProperties: true
          properties:
            draft_id:
              type:
                string
          required:
            - draft_id

    NotificationTemplateWithId:
      allOf:
        - $ref: "#/components/schemas/ReturnedNotificationTemplate"
        - description: NotificationTemplate object with notificationTemplateId. Used to represent server-generated
                       objects
          type: object
          additionalProperties: true
          properties:
            notification_template_id:
              type:
                string
          required:
            - notification_template_id

    NotificationTemplateWithIdList:
      type: array
      items:
        $ref: "#/components/schemas/NotificationTemplateWithId"

    Notification:
      description: Notification sent by user
      type: object
      additionalProperties: false
      properties:
        notification_id:
          type: string
        batch_id:
          type: string
        recipient_id:
          type: string
        group_id:
          type: string
        type:
          type: string
          enum:
            - Telegram
            - SMS
            - Mail
        creation_timestamp:
          type: string
          example: "2024-09-24 13:21:50"
        completion_timestamp:
          type: string
          example: "2024-09-24 13:21:54"
      required:
        - notification_id
        - batch_id
        - recipient_id
        - group_id
        - type
        - creation_timestamp

    NotificationList:
      type: array
      items:
        $ref: "#/components/schemas/Notification"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
