worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

# emergency_notification_system_db_1 is the service name + _ + filename of the ens_schema.sql
dbconnection: 'postgresql://testsuite@localhost:15433/emergency_notification_system_db_1'
